# Generated by Django 6.0.6 on 2026-06-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_EXTRACT_MARKETPLACES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('guest_count', models.IntegerField()),
                ('reservations_time', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
    ]
