# Generated by Django 6.0.6 on 2026-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_HxP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priceReal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stars', models.IntegerField()),
                ('enable', models.BooleanField()),
                ('image', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
    ]
