# Generated by Django 6.0.6 on 2026-07-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_EXTRACT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='historial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API_EXTRACT.historial'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id_HxP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_EXTRACT.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=500)),
                ('id_HxP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_EXTRACT.historial')),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_EXTRACT.user')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(auto_now_add=True)),
                ('marked_as_favorite', models.BooleanField(default=False)),
                ('id_HxP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_EXTRACT.historial')),
                ('id_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_EXTRACT.product')),
            ],
        ),
    ]
